FROM node:24-alpine

WORKDIR /app

ENV NODE_ENV=development
EXPOSE 5000

RUN apk add --no-cache openssl

COPY package.json package-lock.json ./
COPY prisma ./prisma

RUN npm ci --ignore-scripts && ./node_modules/.bin/prisma generate

COPY --chown=node:node tsconfig.json ./
COPY --chown=node:node src ./src

RUN chown -R node:node /app

USER node

CMD ["npm", "run", "dev"]