import { ServiceItem } from "./types";

export const SERVICES_CONFIG: ServiceItem[] = [
  {
    id: "gift-card",
    title: "GIFT CARD",
    category: "Cards & Vouchers",
    iconName: "Gift",
    isSpecial: true, // Golden/special styling as seen in screenshot
    status: "ACTIVE",
    route: "/dashboard/services/gift-card",
    description: "Instant digital gift cards & vouchers for shopping, food, and dining.",
  },
  {
    id: "google-play",
    title: "GOOGLE PLAY",
    category: "Recharge & Bill Pay",
    iconName: "Gamepad2",
    status: "ACTIVE",
    route: "/dashboard/services/google-play",
    description: "Purchase Google Play recharge codes and gaming credits directly.",
  },
  {
    id: "aeps-yes-bank",
    title: "AEPS (YES BANK)",
    category: "Banking & AEPS",
    iconName: "Fingerprint",
    badge: "YES BANK",
    status: "ACTIVE",
    route: "/dashboard/services/aeps-yes-bank",
    description: "Aadhaar Enabled Payment System with Yes Bank gateway: Cash Withdrawal, Balance Enquiry, Mini Statement, Aadhaar Pay.",
  },
  {
    id: "aeps-kotak-bank",
    title: "AEPS (KOTAK BANK)",
    category: "Banking & AEPS",
    iconName: "Fingerprint",
    badge: "KOTAK",
    status: "ACTIVE",
    route: "/dashboard/services/aeps-kotak-bank",
    description: "Aadhaar Enabled Payment System with Kotak Mahindra Bank gateway.",
  },
  {
    id: "mobile-prepaid",
    title: "MOBILE PREPAID",
    category: "Recharge & Bill Pay",
    iconName: "Smartphone",
    status: "ACTIVE",
    route: "/dashboard/services/mobile-prepaid",
    description: "All India prepaid & postpaid mobile recharge across Airtel, Jio, VI, BSNL.",
  },
  {
    id: "dth-recharge",
    title: "DTH RECHARGE",
    category: "Recharge & Bill Pay",
    iconName: "Tv",
    status: "ACTIVE",
    route: "/dashboard/services/dth-recharge",
    description: "Instant DTH recharge for Tata Play, Sun Direct, Airtel Digital TV, Dish TV.",
  },
  {
    id: "bbps",
    title: "BBPS",
    category: "Recharge & Bill Pay",
    iconName: "Receipt",
    badge: "BBPS",
    status: "ACTIVE",
    route: "/dashboard/services/bbps",
    description: "Bharat BillPay: Electricity, Water, Gas, Broadband, Fastag & municipal bills.",
  },
  {
    id: "upi-transfer",
    title: "UPI TRANSFER",
    category: "Money Transfer",
    iconName: "Zap",
    badge: "UPI",
    status: "ACTIVE",
    route: "/dashboard/services/upi-transfer",
    description: "Instant 24x7 UPI payment collections & VPA fund settlements.",
  },
  {
    id: "money-transfer",
    title: "MONEY TRANSFER",
    category: "Money Transfer",
    iconName: "Send",
    badge: "DMT",
    status: "ACTIVE",
    route: "/dashboard/services/money-transfer",
    description: "Domestic Money Transfer (DMT) to any bank account in India in real time.",
  },
];
