import { PrivilegeRecord } from "./types";

export const DEFAULT_PRIVILEGES_LIST: PrivilegeRecord[] = [
  {
    id: "PRV-001",
    userId: "USR-REC-001",
    regNo: "REG-2024-001",
    userName: "Rahul Sharma",
    companyName: "Sharma Digital Pay",
    contactNumber: "9876543210",
    packageName: "Super Retailer Gold",
    userTypeId: "USR-004",
    userTypeName: "Retailer",
    apiPermissions: [
      { apiTypeId: "APT-001", apiTypeName: "Recharge", status: "active" },
      { apiTypeId: "APT-002", apiTypeName: "Bill Payment", status: "active" },
      { apiTypeId: "APT-003", apiTypeName: "DMT (Money Transfer)", status: "active" },
      { apiTypeId: "APT-004", apiTypeName: "AEPS", status: "inactive" },
    ],
    status: "active",
  },
  {
    id: "PRV-002",
    userId: "USR-REC-002",
    regNo: "REG-2024-002",
    userName: "Amit Verma",
    companyName: "Verma Telecom Services",
    contactNumber: "9812345678",
    packageName: "Distributor Diamond",
    userTypeId: "USR-003",
    userTypeName: "Distributor",
    apiPermissions: [
      { apiTypeId: "APT-001", apiTypeName: "Recharge", status: "active" },
      { apiTypeId: "APT-002", apiTypeName: "Bill Payment", status: "active" },
      { apiTypeId: "APT-003", apiTypeName: "DMT (Money Transfer)", status: "active" },
      { apiTypeId: "APT-004", apiTypeName: "AEPS", status: "active" },
    ],
    status: "active",
  },
  {
    id: "PRV-003",
    userId: "USR-REC-003",
    regNo: "REG-2024-003",
    userName: "Pooja Patel",
    companyName: "Patel Fintech Solutions",
    contactNumber: "9898765432",
    packageName: "API Merchant Platinum",
    userTypeId: "USR-005",
    userTypeName: "API User / Merchant",
    apiPermissions: [
      { apiTypeId: "APT-001", apiTypeName: "Recharge", status: "active" },
      { apiTypeId: "APT-002", apiTypeName: "Bill Payment", status: "inactive" },
      { apiTypeId: "APT-003", apiTypeName: "DMT (Money Transfer)", status: "active" },
      { apiTypeId: "APT-004", apiTypeName: "AEPS", status: "active" },
    ],
    status: "active",
  },
  {
    id: "PRV-004",
    userId: "USR-REC-004",
    regNo: "REG-2024-004",
    userName: "Suresh Kumar",
    companyName: "SK Multi-Services Hub",
    contactNumber: "9723456789",
    packageName: "Master Distributor Elite",
    userTypeId: "USR-002",
    userTypeName: "Master Distributor",
    apiPermissions: [
      { apiTypeId: "APT-001", apiTypeName: "Recharge", status: "active" },
      { apiTypeId: "APT-002", apiTypeName: "Bill Payment", status: "active" },
      { apiTypeId: "APT-003", apiTypeName: "DMT (Money Transfer)", status: "inactive" },
      { apiTypeId: "APT-004", apiTypeName: "AEPS", status: "inactive" },
    ],
    status: "active",
  },
  {
    id: "PRV-005",
    userId: "USR-REC-005",
    regNo: "REG-2024-005",
    userName: "Vikas Gupta",
    companyName: "Gupta Online Center",
    contactNumber: "9632587410",
    packageName: "Retailer Silver",
    userTypeId: "USR-004",
    userTypeName: "Retailer",
    apiPermissions: [
      { apiTypeId: "APT-001", apiTypeName: "Recharge", status: "active" },
      { apiTypeId: "APT-002", apiTypeName: "Bill Payment", status: "active" },
      { apiTypeId: "APT-003", apiTypeName: "DMT (Money Transfer)", status: "inactive" },
      { apiTypeId: "APT-004", apiTypeName: "AEPS", status: "inactive" },
    ],
    status: "active",
  },
];
