export const requestsFieldsConfig = [
  {
    key: "requestAmount",
    label: "Request Amount *",
    type: "number",
    placeholder: "Enter request amount...",
    required: true,
  },
  {
    key: "requestFrom",
    label: "Request From *",
    type: "text",
    placeholder: "Admin",
    required: true,
  },
  {
    key: "bankName",
    label: "Bank Name (Beneficiary) *",
    type: "text",
    placeholder: "Select or enter beneficiary bank...",
    required: true,
  },
  {
    key: "transactionId",
    label: "Transaction ID / Ref No. *",
    type: "text",
    placeholder: "Enter Google Pay / UPI transaction ID...",
    required: true,
  },
  {
    key: "paymentBy",
    label: "Payment By (App Name) *",
    type: "text",
    placeholder: "Google Pay, PhonePe, Paytm, etc...",
    required: true,
  },
  {
    key: "depositDate",
    label: "Deposit Date *",
    type: "date",
    placeholder: "Select date of payment...",
    required: true,
  },
  {
    key: "remarks",
    label: "Remarks / Message",
    type: "text",
    placeholder: "Enter fund request notes or remarks...",
    required: false,
  },
] as const;
