import { MerchantApiRecord } from "./types";

export const DEFAULT_MERCHANT_RETAILERS: MerchantApiRecord[] = [
  {
    id: "RET-001",
    partnerId: "USR-REC-003",
    partnerName: "Pooja Patel",
    partnerCompanyName: "Patel Fintech Solutions",
    retailerCode: "REG-2024-101",
    retailerName: "Rajesh Kumar",
    shopName: "Rajesh Mobile & Pay",
    contactNo: "9876543201",
    email: "rajesh.pay@gmail.com",
    panNo: "ABCDE1234F",
    aadhaarNo: "987654321098",
    kycStatus: "verified",
    isOtpVerify: "Y",
    isBlocked: false,
    status: "active",
    registeredAt: "2024-02-10",
    apiKey: "mk_live_8f7b2c91a034de71",
    callbackUrl: "https://api.rajeshpay.com/webhook",
  },
  {
    id: "RET-002",
    partnerId: "USR-REC-003",
    partnerName: "Pooja Patel",
    partnerCompanyName: "Patel Fintech Solutions",
    retailerCode: "REG-2024-102",
    retailerName: "Sanjay Gupta",
    shopName: "Gupta Telecom & Banking",
    contactNo: "9876543202",
    email: "sanjay.gupta@gmail.com",
    panNo: "FGHIJ5678K",
    aadhaarNo: "876543210987",
    kycStatus: "pending",
    isOtpVerify: "Y",
    isBlocked: false,
    status: "active",
    registeredAt: "2024-02-14",
    apiKey: "mk_live_3e1a7d88c942fb65",
    callbackUrl: "https://api.guptatelecom.in/callback",
  },
  {
    id: "RET-003",
    partnerId: "USR-REC-003",
    partnerName: "Pooja Patel",
    partnerCompanyName: "Patel Fintech Solutions",
    retailerCode: "REG-2024-103",
    retailerName: "Manish Tiwari",
    shopName: "Tiwari Digital Kendra",
    contactNo: "9876543203",
    email: "manish.kendra@gmail.com",
    panNo: "KLMNO9012P",
    aadhaarNo: "765432109876",
    kycStatus: "rejected",
    isOtpVerify: "N",
    isBlocked: true,
    status: "blocked",
    registeredAt: "2024-01-20",
    apiKey: "mk_live_9a4b2c11d087fe32",
    callbackUrl: "https://api.tiwarikendra.com/webhook",
  },
  {
    id: "RET-004",
    partnerId: "USR-REC-001",
    partnerName: "Rahul Sharma",
    partnerCompanyName: "Sharma Digital Pay",
    retailerCode: "REG-2024-104",
    retailerName: "Vikram Singh",
    shopName: "Singh Multi-Services",
    contactNo: "9876543204",
    email: "vikram.singh@gmail.com",
    panNo: "PQRST3456U",
    aadhaarNo: "654321098765",
    kycStatus: "verified",
    isOtpVerify: "Y",
    isBlocked: false,
    status: "active",
    registeredAt: "2024-02-01",
    apiKey: "mk_live_5c3d2e11a998cb44",
    callbackUrl: "https://api.singhservices.com/notify",
  },
  {
    id: "RET-005",
    partnerId: "USR-REC-001",
    partnerName: "Rahul Sharma",
    partnerCompanyName: "Sharma Digital Pay",
    retailerCode: "REG-2024-105",
    retailerName: "Deepak Choudhary",
    shopName: "Choudhary Online Services",
    contactNo: "9876543205",
    email: "deepak.online@gmail.com",
    panNo: "UVWXY7890Z",
    aadhaarNo: "543210987654",
    kycStatus: "pending",
    isOtpVerify: "Y",
    isBlocked: false,
    status: "active",
    registeredAt: "2024-02-18",
    apiKey: "mk_live_7e8f9a01b234cd56",
    callbackUrl: "https://api.choudharyonline.in/callback",
  },
  {
    id: "RET-006",
    partnerId: "USR-REC-002",
    partnerName: "Amit Verma",
    partnerCompanyName: "Verma Telecom Services",
    retailerCode: "REG-2024-106",
    retailerName: "Anil Mehra",
    shopName: "Mehra Recharge Hub",
    contactNo: "9876543206",
    email: "anil.mehra@gmail.com",
    panNo: "ABCDE9876X",
    aadhaarNo: "432109876543",
    kycStatus: "verified",
    isOtpVerify: "Y",
    isBlocked: false,
    status: "active",
    registeredAt: "2024-01-15",
    apiKey: "mk_live_1a2b3c4d5e6f7a8b",
    callbackUrl: "https://api.mehrahub.com/webhook",
  },
];
